'use strict';
const assert = require('node:assert/strict');
require('fake-indexeddb/auto');
global.Dexie = require('../vendor/dexie-4.4.5.min.js');
global.JSZip = require('../vendor/jszip-3.10.1.min.js');
global.location = { pathname: '/teste' };
global.NOME_DELA = 'Teste'; global.NOME_DELE = 'Teste';
global.gerarIdUnico = p => `${p}_${require('node:crypto').randomUUID()}`;
global.obterOuCriarDataPrimeiroAcesso = async () => '2026-01-01';
global.chaveConfigPodeSerApagada = () => false;
const local = new Map();
global.localStorage = { get length() { return local.size; }, key: i => [...local.keys()][i], getItem: k => local.get(k) ?? null, setItem: (k,v) => local.set(k,String(v)), removeItem: k => local.delete(k) };
const banco = require('../js/db.js'); Object.assign(global, banco);
const backup = require('../js/export.js');
const cartas = require('../js/mesversarios.js');
const atividade = require('../scripts/verificar-atividade-supabase.js');
(async () => {
    await db.open();
    const dados = { mes: 2, data: '2026-10-01', titulo: 'Dois meses', texto: 'Meu amor,\n<script>texto sem execução</script>' };
    const [a,b] = await Promise.all([cartas.guardarTextoMesversario(dados), cartas.guardarTextoMesversario({ ...dados, mes: 1 })]);
    assert.notEqual(a.id,b.id);
    assert.equal((await cartas.obterTextosMesversario()).length,2);
    const editada = await cartas.guardarTextoMesversario({ ...dados, texto: 'Carta revisada' },a);
    assert.equal(editada.id,a.id); assert.ok(editada.atualizadoEm>a.atualizadoEm);
    const zip = await backup.gerarBackupZipBlob();
    const manifesto = (await backup.validarEPrepararBackupZip(await zip.arrayBuffer())).manifest;
    assert.equal(JSON.parse(manifesto.configuracoes['aurora_mesversario_item:'+a.id]).texto,'Carta revisada');
    await db.configuracoes.clear(); local.clear();
    await backup.aplicarBackupDeZip(await zip.arrayBuffer());
    await backup.aplicarBackupDeZip(await zip.arrayBuffer());
    assert.equal((await cartas.obterTextosMesversario()).length,2);
    await salvarConfiguracao('aurora_mesversario_item:'+a.id,JSON.stringify({ ...editada,excluidoEm:Date.now(),atualizadoEm:Date.now() }),true);
    assert.equal((await cartas.obterTextosMesversario()).length,1);
    const salvar = global.salvarConfiguracao;
    global.salvarConfiguracao = async () => false;
    await assert.rejects(()=>cartas.guardarTextoMesversario(dados),/Não foi possível/);
    global.salvarConfiguracao = salvar;
    for (const invalid of [{mes:0},{mes:1.5},{texto:' '},{texto:'x'.repeat(20001)},{data:'2026-02-30'}]) assert.throws(()=>cartas.validarTextoMesversario({...dados,...invalid}));
    let tentativas=0;
    await assert.rejects(()=>atividade.consultarComRetentativas('https://offline.invalid',{},()=>{},async()=>{tentativas++;return {ok:false,status:503,json:async()=>({})};},async()=>{}),/HTTP 503/);
    assert.equal(tentativas,3);
    const chamadas=[];
    const ok=await atividade.verificarAtividade({fetchFn:async (url,opcoes)=>{chamadas.push({url,opcoes});return {ok:true,json:async()=>url.includes('/rpc/')?true:{revisao:1,geracaoAtual:{id:'teste'}}};},esperar:async()=>{}});
    assert.equal(ok.bancoConsultado,true); assert.equal(chamadas.length,2);
    assert.equal(chamadas[0].opcoes.method,'POST');
    assert.ok(chamadas[0].url.endsWith('/rpc/poloni_verificar_atividade'));
    await assert.rejects(()=>atividade.verificarAtividade({fetchFn:async()=>({ok:true,json:async()=>false}),esperar:async()=>{}}),/banco não confirmou/);
    const pendente = await atividade.verificarAtividade({ permitirRpcPendente: true, esperar: async()=>{}, fetchFn: async url=>url.includes('/rpc/') ? {ok:false,status:404,json:async()=>({code:'PGRST202'})} : {ok:true,json:async()=>({revisao:1,geracaoAtual:{id:'teste'}})} });
    assert.equal(pendente.bancoConsultado,false); assert.equal(pendente.ativacaoSqlPendente,true);
    await assert.rejects(()=>atividade.verificarAtividade({ permitirRpcPendente: true, esperar: async()=>{}, fetchFn: async()=>({ok:false,status:403,json:async()=>({})}) }),/HTTP 403/);
    console.log('OK  mesversários: criação concorrente, edição, backup/restore sem duplicação, exclusão, validação e falha de escrita');
    console.log('OK  atividade Supabase: consulta RPC, validação de saúde, prazo e retentativas limitadas');
    await db.delete();
})().catch(async e=>{console.error(e);await db.delete();process.exitCode=1;});
